Newmachine
Simple-Automation-Testing/training-camp pull request #11
Opened 2021-05-31 16:02 UTC by Andrei1982

- added waitForTime method for debugging
- added new test case to tables spec file
- added initElement method

2021-06-02 14:00 UTC, potapovDim requested changes

2021-06-02 14:08 UTC, potapovDim requested changes

2021-06-02 14:08 UTC, potapovDim commented on machines/testing/lib/runner/runner.js
> +
wrappedIt.only = wrappedOnly

2021-06-13 16:07 UTC, potapovDim requested changes

2021-06-13 16:07 UTC, potapovDim commented on machines/testing/specs/index.spec.js
> +		it.only("should login an exisiting user and redirect him to Tables page", async () => {
remove only

2021-06-13 16:07 UTC, potapovDim commented on machines/testing/specs/table.spec.js
> +		it.only("should login as admin and add a new machine", async () => {
remove only

2021-06-13 16:14 UTC, Andrei1982 commented on machines/testing/specs/table.spec.js
> +		it.only("should login as admin and add a new machine", async () => {
removed

2021-06-13 16:14 UTC, Andrei1982 commented on machines/testing/specs/index.spec.js
> +		it.only("should login an exisiting user and redirect him to Tables page", async () => {
removed

2021-06-13 16:49 UTC, potapovDim approved these changes

2021-06-13 16:49 UTC, merged